@echo off
echo Starting Ultra AI DJ...
echo 1. Starting Backend API...
start "AI Backend" cmd /k "python server/api.py"
echo 2. Starting Frontend UI...
cd client
echo Installing dependencies if missing...
call npm install
echo Starting React App...
start "Ultra UI" cmd /k "npm run dev"
echo Done! Check your browser.
